version: '2'
services:
  configserver:
    image: goita/license-confsrv:chapter3
    ports:
       - "8888:8888"
    environment:
      ENCRYPT_KEY: "IMSYMMETRICNOW"
  database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB:       "eagle_eye_local"
  licensingservice:
    image: goita/local-licensing-service:chapter3
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
      ENCRYPT_KEY: "IMSYMMETRICNOW"
