server:
  port: 5555

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.thoughtmechanix: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix:  /api
#  ignored-services: '*' # This can be used to ignore automatically mapped services
  routes:
#    externalauthservice:
#      path: /external-auth/**
#      url: https://external-auth:8093
    organizationservice: /organization/**
