spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

#In case you just use plain oauth2 security without JWT
#security:
#  oauth2:
#    resource:
#      userInfoUri: http://localhost:8901/auth/user

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

        